apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Release.Name}}-route
  annotations:
    "haproxy.router.openshift.io/balance": "roundrobin"
    {{/* Disables the 'sticky' routing to make sure requests end in the same pod. */}}
    "haproxy.router.openshift.io/disable_cookies": "true"
spec:
  host: {{.Release.Name}}.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{.Release.Name}}-service