apiVersion: v1
kind: Service
metadata:
  name: graalvmtest-service
  labels:
    app: graalvmtest-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: graalvmtest-app